--                             REVENUE GENERATED BY GENDER

			select gender, sum(purchase_amount) as revenue from customer
			group by gender;
			
            
--   				CUSTOMER USED DISCOUNT STILL SPENT MORE THAN AVG. PURCHASE

--SELECT customer_id, purchase_amount
--from customer
--where discount_applied = "YES" &
--purchase_amount > avg(purchase_amount) ;

--- SUBQUERY
SELECT (customer_id), (purchase_amount)
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount > 
  (
SELECT AVG(purchase_amount)
FROM customer
  );
	
      
--                                      TOP 5 PRODUCTS WITH HIGHEST RATING THAN AVG. RATING

SELECT (item_purchased), (review_rating)
FROM customer
WHERE review_rating > (
        SELECT AVG(review_rating)
        FROM customer)
 limit 5;

--									COMPARE	AVG. PURCH AMT BETWEEN STANDARD AND EXPRESS SHIPPING

SELECT * FROM customer;

SELECT shipping_type,ROUND(avg(purchase_amount),2) FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- 							SUBSCRIBED CUST SPENDING MORE. COMPARE AVG. SPEND AND TOTAL REVENUE BETWEEN SUBS & NON-SUBS 

SELECT subscription_status,
COUNT(customer_id) CUSTOMER_COUNT,
ROUND(AVG(purchase_amount),2) AVG_PURCHASE,
SUM(purchase_amount) TOTAL_REVENUE
FROM customer
GROUP BY subscription_status
ORDER BY TOTAL_REVENUE,AVG_PURCHASE DESC;


--					5 PRODUCTS HAVING HIGHEST % OF PURCHASE WITH DISCOUNT APPLIED

select * from customer;
SELECT item_purchased,
ROUND(sum(CASE WHEN discount_applied = 'YES'THEN 1 ELSE 0 END)/COUNT(*) * 100,2) DISC_RATE
FROM customer
GROUP BY item_purchased
ORDER BY DISC_RATE DESC
LIMIT 5;

--						SEGMENT CUSTOMERS INTO NEW, RETURNING, LOYAL BASED ON THEIR TOTAL NUMBER OF PREV. PURCHASE & SHOW COUNT OF EACH SEGMENT
--CTE REQUIRED

WITH CUSTOMER_TYPE AS 
(
SELECT customer_id,previous_purchases,
CASE
WHEN previous_purchases = 1 THEN 'NEW'
WHEN previous_purchases BETWEEN 2 AND 10 
THEN 'RETURNING'
ELSE 'LOYAL'
END AS CUSTOMER_SEGMENT
FROM customer
)
SELECT CUSTOMER_SEGMENT,COUNT(*) CUSTOMER_COUNT FROM CUSTOMER_TYPE GROUP BY CUSTOMER_SEGMENT;

--									TOP 3 MOST PURCHASED PRODUCTS WITHIN EACH CATEGORY

--USING WINDOWS AND CTE function

WITH ITEM_COUNT AS 
(SELECT category, item_purchased, count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank from customer
group by category, item_purchased)

select item_rank, category, item_purchased, total_orders from item_count
where item_rank <= 3;

--							CUSTOMERS WHO ARE REPEAT BUYERS(MORE THAN 5 PREV. PURCHASE) ALSO LIKELY TO SUBSCRIBE?

SELECT SUBSCRIPTION_STATUS, COUNT(CUSTOMER_ID) AS REPEAT_BUYERS
FROM CUSTOMER
WHERE PREVIOUS_PURCHASES > 5
GROUP BY SUBSCRIPTION_STATUS;

--					REVENUE BY AGE GROUP

SELECT AGE_GROUP, SUM(PURCHASE_AMOUNT) TOTAL_REVENUE FROM CUSTOMER
GROUP BY AGE_GROUP
ORDER BY TOTAL_REVENUE DESC;